# vi: set ft=yaml ts=2 expandtab:
---

- name: load OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: config.txt is present
  template:
    src: config.txt.j2
    dest: /boot/config.txt
  notify: reboot

- name: poe hat fan
  block:

    - name: the device tree source is present
      copy:
        src: rpi-poe-overlay.dts
        dest: /root/rpi-poe-overlay.dts
      register: _raspberry_poe_overlay
      notify: compile dtb

    - name: get mtime from dtb
      stat:
        path: /boot/overlays/rpi-poe.dtbo
      register: _rpi_poe_dtb

    - name: get mtime from dts
      stat:
        path: /boot/overlays/rpi-poe-overlay.dts
      register: _rpi_poe_dts

    - name: debug _rpi_poe_dtb
      debug: var=_rpi_poe_dtb
      tags:
        - never
        - debug

    - name: debug _rpi_poe_dts
      debug: var=_rpi_poe_dts
      tags:
        - never
        - debug

    - name: compile dtb if necessary
      when: (not _rpi_poe_dts.stat.exists) or (_rpi_poe_dts.stat.mtime < _rpi_poe_dtb.stat.mtime)
      command: /bin/true
      notify: compile dtb
...
