# vi: set ft=yaml ts=2 expandtab:
---

- name: load OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: config.txt is present
  template:
    src: config.txt.j2
    dest: /boot/config.txt
  notify: reboot

- name: cpufreq governor is set
  lineinfile:
    path: "{{ __rc_local }}"
    line: echo conservative >/sys/devices/system/cpu/cpufreq/policy0/scaling_governor
    regexp: "^echo conservative >/sys/devices/system/cpu/cpufreq/policy0/scaling_governor"
    mode: ugo+x

- name: poe hat fan
  block:

    - name: device tree compiler is installed
      package:
        name: dtc
        state: installed

    - name: the device tree source is present
      file:
        src: rpi-poe-overlay.dts
        dest: /boot/overlays/rpi-poe-overlay.dts"
        backup: true
      register: _raspberry_poe_overlay
      notify: compile rpi_poe_dtbo

...
